DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE white_cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  phrase TEXT NOT NULL,
);

CREATE TABLE black_cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  phrase TEXT NOT NULL,
);